apiVersion: v1
kind: Pod
metadata:
  name: centos-pod-labeled
  labels:
    app: centos-pod-labeled
spec:
  nodeSelector:
    type: "gpu"
  containers:
  - image: centos  
    name: centos-pod
    stdin: true
    tty: true
